version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/packages/pop_pop"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(pop_pop):"

  - package-ecosystem: "pub"
    directory: "/packages/pop_pop_components"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(pop_pop_components):"