include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  strong-mode:
    implicit-dynamic: false
    implicit-casts: false
  errors:
    todo: ignore
    missing_required_param: error
linter:
  rules:
    - constant_identifier_names
    - sort_pub_dependencies
