name: pop_pop_sample
description: A demo project implementing the base pop_pop and components packages.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  audioplayers: ^0.20.1
  fimber: ^0.6.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed: ^1.1.1
  get_it: ^7.2.0
  go_router: ^3.0.1
  google_fonts: ^2.3.1
  isar: ^2.2.1
  isar_flutter_libs: ^2.2.1
  package_info_plus: ^1.4.0
  path_provider: ^2.0.9
  pop_pop: ^1.0.0
  pop_pop_components: ^0.1.1
  provider: ^6.0.1
  sentry_flutter: ^6.3.0

dev_dependencies:
  build_runner: any
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.13.0
  isar_generator: ^2.2.1
  mocktail: ^0.2.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/mp3/
    - assets/images/
    - google_fonts/
