name: pop_pop_components
version: 0.1.1
description: Prebuilt components implementing pop_pop
homepage: https://github.com/jamieastley/pop_pop

dependencies:
  flutter:
    sdk: flutter

  pop_pop: ^1.0.0

  provider: ^6.0.1
  rxdart: ^0.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  mocktail: ">=0.2.0 <2.0.0"

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
  uses-material-design: true
