name: pop_pop_analyze

on:
  push:
    tags-ignore:
      - "pop_pop*"
    paths:
      - "packages/pop_pop/**"
      - ".github/workflows/pop_pop_analyze.yaml"

  pull_request:
    paths:
      - "packages/pop_pop/**"
      - ".github/workflows/pop_pop_analyze.yaml"

jobs:
  analyze:
    defaults:
      run:
        working-directory: packages/pop_pop

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get
      - run: flutter analyze
