name: pop_pop

on:
  push:
    branches:
      - "master"
    paths:
      - "packages/pop_pop/**"
      - ".github/workflows/pop_pop.yaml"

  pull_request:
    paths:
      - "packages/pop_pop/**"
      - ".github/workflows/pop_pop.yaml"

jobs:
  analyze:
    defaults:
      run:
        working-directory: packages/pop_pop

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get
      - run: flutter analyze
