name: pop_pop

on:
  push:
    paths:
      - "packages/pop_pop/**"
      - ".github/workflows/pop_pop.yaml"

  pull_request:
    paths:
      - "packages/pop_pop/**"
      - ".github/workflows/pop_pop.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/pop_pop

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.0

      # setup env
      - run: flutter pub get
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - run: pub global activate remove_from_coverage

      - run: flutter analyze
