name: pop_pop_test

on:
  push:
#    branches:
#      - master
#    paths:
#      - "packages/pop_pop/**"
#      - ".github/workflows/**"

  pull_request:
    paths:
      - "packages/pop_pop/**"
      - ".github/workflows/**"

jobs:
  test:
    defaults:
      run:
        working-directory: packages/pop_pop

    runs-on: macos-11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
#          flutter-version: '2.8.1'
          channel: "stable"

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --coverage

      - name: Upload golden test failures
        uses: actions/upload-artifact@v4
        with:
          name: test-failures
          path: test/failures/
